# Generated by Django 4.2.7 on 2024-01-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_role',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
