# Generated by Django 5.0.1 on 2024-03-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_images'),
        ),
    ]
