# Generated by Django 4.2.7 on 2024-01-10 06:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('discount', models.FloatField()),
                ('location_coordination', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=100)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derleng.category')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('number', models.BigIntegerField()),
                ('expire_date', models.TimeField()),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('uri_image', models.CharField(max_length=50)),
                ('order_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('last_login', models.TimeField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derleng.user_role')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Rating must be greater than or equal to 0.'), django.core.validators.MaxValueValidator(5, message='Rating must be less than or equal to 5.')])),
                ('comment', models.CharField(max_length=100)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derleng.package')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derleng.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derleng.user')),
            ],
        ),
        migrations.CreateModel(
            name='package_service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derleng.package')),
            ],
        ),
        migrations.CreateModel(
            name='Package_schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derleng.package')),
            ],
        ),
        migrations.CreateModel(
            name='Package_image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uri_image', models.CharField(max_length=100)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derleng.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derleng.user'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_ammount', models.IntegerField()),
                ('booking_date', models.TimeField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derleng.package')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derleng.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_accept', models.BooleanField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derleng.cart')),
            ],
        ),
    ]
