# Generated by Django 4.2.7 on 2024-01-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(default='package', max_length=30),
            preserve_default=False,
        ),
    ]
