# Generated by Django 4.2.7 on 2024-01-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0002_package_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='package_image',
            old_name='package_id',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='package_schedule',
            old_name='package_id',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='package_service',
            old_name='package_id',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='package_id',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
