# Generated by Django 4.2.7 on 2024-01-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0003_rename_cart_id_booking_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_image',
            name='image',
            field=models.ImageField(max_length=500, upload_to='images/package_images/'),
        ),
    ]
