# Generated by Django 5.0.1 on 2024-01-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0004_alter_customer_payments_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_refunds',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
