# Generated by Django 4.2.7 on 2024-01-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0004_alter_package_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_unavailable_date',
            name='unavailable_at',
            field=models.DateField(),
        ),
    ]
