# Generated by Django 4.2.7 on 2024-01-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0005_alter_package_unavailable_date_unavailable_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='package',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
