# Generated by Django 5.0.1 on 2024-01-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0006_booking_details_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_method',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
