# Generated by Django 4.2.7 on 2024-01-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0007_package_service_is_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
    ]
