# Generated by Django 4.2.7 on 2024-01-20 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0008_package_is_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30, unique=True)),
                ('percentage_of_sale_price', models.FloatField()),
            ],
        ),
    ]
