# Generated by Django 5.0.1 on 2024-01-31 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0008_remove_seller_transactions_stripe_admin_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_details',
            old_name='card',
            new_name='cart',
        ),
    ]
