# Generated by Django 4.2.7 on 2024-01-20 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0009_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='commission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='derleng.commission'),
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='derleng.category'),
        ),
    ]
