# Generated by Django 5.0.1 on 2024-02-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0010_package_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer_ammount',
            new_name='customer_amount',
        ),
    ]
