# Generated by Django 4.2.7 on 2024-01-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0010_package_commission_alter_package_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='order_number',
        ),
    ]
