# Generated by Django 4.2.7 on 2024-01-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0011_remove_thumbnail_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_method',
            name='number',
        ),
        migrations.RemoveField(
            model_name='payment_method',
            name='token',
        ),
        migrations.AddField(
            model_name='payment_method',
            name='brand',
            field=models.CharField(default='VISA', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_method',
            name='exp_month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_method',
            name='exp_year',
            field=models.IntegerField(default=26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_method',
            name='last4',
            field=models.CharField(default='1234', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_method',
            name='payment_method_id',
            field=models.CharField(default='token_id', max_length=255),
            preserve_default=False,
        ),
    ]
