# Generated by Django 5.0.1 on 2024-03-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0012_payment_method_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
