# Generated by Django 4.2.7 on 2024-01-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0012_remove_payment_method_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_method',
            name='customer_id',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
    ]
