# Generated by Django 4.2.7 on 2024-01-25 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('derleng', '0013_payment_method_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_details',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_accept',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment_method',
            name='holder_name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Seller_transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission', models.FloatField()),
                ('amount', models.FloatField()),
                ('amount_received', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('stripe_admin_account_id', models.CharField(max_length=255)),
                ('stripe_payment_method_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=30)),
                ('created', models.BigIntegerField()),
                ('booking_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='derleng.booking_details')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_payments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('amount_received', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('stripe_payment_method_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=30)),
                ('created', models.BigIntegerField()),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='derleng.booking')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking_details',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='derleng.booking'),
        ),
        migrations.AddField(
            model_name='booking_details',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='derleng.cart'),
        ),
    ]
