# Generated by Django 5.0.1 on 2024-03-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0013_alter_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
