# Generated by Django 4.2.7 on 2024-01-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0014_booking_details_remove_booking_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='booking_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
