# Generated by Django 4.2.7 on 2024-01-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0015_alter_cart_booking_date_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide_register_info',
            name='cv',
            field=models.FileField(max_length=1000, upload_to='files/guide_register_info/'),
        ),
        migrations.AlterField(
            model_name='profile_image',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='images/profile_images'),
        ),
    ]
