# Generated by Django 4.2.7 on 2024-01-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0016_alter_guide_register_info_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile_image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
