# Generated by Django 5.0.1 on 2024-03-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('derleng', '0022_review_booking_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking_details',
        ),
    ]
